"use strict";
function linkControl(l){const a=nodeById(l.a),b=nodeById(l.b);return l.control||{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function linkPath(l){const a=nodeById(l.a),b=nodeById(l.b),c=linkControl(l);return`M ${a.x} ${a.y} Q ${c.x} ${c.y} ${b.x} ${b.y}`}
function rootPatchPath(n,dir,width,progress=1){if(!n||progress<=.01)return null;const u=unit(dir.x,dir.y),v={x:-u.y,y:u.x},half=width/2,p=clamp(progress,0,1),fullSide=clamp(width*.92,half+3,Math.min(n.r*.48,width*1.08)),side=half+(fullSide-half)*p,radial0=Math.sqrt(Math.max(1,n.r*n.r-side*side)),inset=4*p,radial=Math.max(1,radial0-inset),rootLen=clamp(width*1.18,20,44)*p,p1={x:n.x+u.x*radial+v.x*side,y:n.y+u.y*radial+v.y*side},p2={x:n.x+u.x*radial-v.x*side,y:n.y+u.y*radial-v.y*side},tc={x:n.x+u.x*(n.r+rootLen),y:n.y+u.y*(n.r+rootLen)},q1={x:tc.x+v.x*half,y:tc.y+v.y*half},q2={x:tc.x-v.x*half,y:tc.y-v.y*half},t1=unit(u.x*side-v.x*radial0,u.y*side-v.y*radial0),t2=unit(u.x*side+v.x*radial0,u.y*side+v.y*radial0),k1=Math.max(5,rootLen*.68),k2=Math.max(4,rootLen*.46),c1={x:p1.x+t1.x*k1,y:p1.y+t1.y*k1},c2={x:q1.x-u.x*k2,y:q1.y-u.y*k2},c3={x:q2.x-u.x*k2,y:q2.y-u.y*k2},c4={x:p2.x+t2.x*k1,y:p2.y+t2.y*k1};return`M ${p1.x} ${p1.y} C ${c1.x} ${c1.y} ${c2.x} ${c2.y} ${q1.x} ${q1.y} L ${q2.x} ${q2.y} C ${c3.x} ${c3.y} ${c4.x} ${c4.y} ${p2.x} ${p2.y} Z`}
function linkRootPaths(l){const a=nodeById(l.a),b=nodeById(l.b),w=linkWidth(l);if(!a||!b)return[];return[{d:rootPatchPath(a,{x:b.x-a.x,y:b.y-a.y},w)},{d:rootPatchPath(b,{x:a.x-b.x,y:a.y-b.y},w)}].filter(x=>x.d)}
function quadTangent(l,t){const a=nodeById(l.a),b=nodeById(l.b),c=linkControl(l),u=1-t;return{x:2*(u*(c.x-a.x)+t*(b.x-c.x)),y:2*(u*(c.y-a.y)+t*(b.y-c.y))}}
function linkCrossings(upper,lower){const hits=[];let pa=quadPoint(upper,0);for(let i=1;i<=32;i++){const ta=i/32,qa=quadPoint(upper,ta);let pb=quadPoint(lower,0);for(let j=1;j<=32;j++){const tb=j/32,qb=quadPoint(lower,tb),hit=segmentIntersection(pa,qa,pb,qb);if(hit&&ta>.08&&ta<.92&&tb>.08&&tb<.92&&!hits.some(h=>dist(h.x,h.y,hit.x,hit.y)<10/view.scale)){const ut=(i-.5)/32,lt=(j-.5)/32,tup=quadTangent(upper,ut),tlp=quadTangent(lower,lt),tu=unit(tup.x,tup.y),tl=unit(tlp.x,tlp.y),sin=Math.abs(tu.x*tl.y-tu.y*tl.x);hits.push({x:hit.x,y:hit.y,t:ut,sin})}pb=qb}pa=qa}return hits}
function localLinkSegment(l,t,fullLen){const tg=quadTangent(l,t),speed=Math.hypot(tg.x,tg.y)||1,dt=clamp((fullLen/2)/speed,.004,.065),a=quadPoint(l,clamp(t-dt,0,1)),m=quadPoint(l,clamp(t,0,1)),b=quadPoint(l,clamp(t+dt,0,1));return`M ${a.x} ${a.y} Q ${m.x} ${m.y} ${b.x} ${b.y}`}
function mergeBridge(m,shadow=false){const a=nodeById(m.a),b=nodeById(m.b);if(!a||!b)return null;const u=unit(b.x-a.x,b.y-a.y),start={x:a.x+u.x*(a.r*.64),y:a.y+u.y*(a.r*.64)},end={x:b.x-u.x*(b.r*.64),y:b.y-u.y*(b.r*.64)},width=clamp(Math.min(a.r,b.r)*.72,22,48);return sEl("path",{d:`M ${start.x} ${start.y} L ${end.x} ${end.y}`,class:shadow?"":"merge-body",stroke:shadow?"#000":undefined,"stroke-width":width,"stroke-linecap":"round"})}
function hiddenNodeMap(){const map=new Map();const arr=sortedNodes();for(const n of arr){let top=null;for(const other of arr){if(other.id===n.id||(other.z??0)<=(n.z??0))continue;if(dist(n.x,n.y,other.x,other.y)+n.r<=other.r+.5){if(!top||(other.z??0)>(top.z??0))top=other}}if(top)map.set(n.id,top.id)}return map}
function circleOverlapArc(top,bottom){const dx=bottom.x-top.x,dy=bottom.y-top.y,d=Math.hypot(dx,dy);if(d<=1e-6)return null;if(d>=top.r+bottom.r)return null;if(d+top.r<=bottom.r)return{full:true};if(d+bottom.r<=top.r)return null;const theta=Math.atan2(dy,dx),c=clamp((d*d+top.r*top.r-bottom.r*bottom.r)/(2*d*top.r),-1,1),alpha=Math.acos(c),a1=theta-alpha,a2=theta+alpha,p1={x:top.x+Math.cos(a1)*top.r,y:top.y+Math.sin(a1)*top.r},p2={x:top.x+Math.cos(a2)*top.r,y:top.y+Math.sin(a2)*top.r};return{full:false,d:`M ${p1.x} ${p1.y} A ${top.r} ${top.r} 0 0 1 ${p2.x} ${p2.y}`}}
function renderShadow(){shadowLayer.replaceChildren();for(const l of links){shadowLayer.appendChild(sEl("path",{d:linkPath(l),fill:"none",stroke:"#000","stroke-width":linkWidth(l),"stroke-linecap":"round","stroke-linejoin":"round"}));for(const rp of linkRootPaths(l))shadowLayer.appendChild(sEl("path",{d:rp.d,fill:"#000"}))}for(const m of attachments){const e=mergeBridge(m,true);if(e)shadowLayer.appendChild(e)}for(const n of nodes)shadowLayer.appendChild(sEl("circle",{cx:n.x,cy:n.y,r:n.r,fill:"#000"}))}
function renderLinks(fast=false){linksLayer.replaceChildren();mergeLayer.replaceChildren();const ordered=[...links].sort((a,b)=>(a.seq??0)-(b.seq??0));for(let i=0;i<ordered.length;i++){const l=ordered[i];if(!fast)for(let j=0;j<i;j++){const lower=ordered[j];for(const hit of linkCrossings(l,lower)){const fullLen=clamp((linkWidth(lower)+3)/Math.max(hit.sin,.28),linkWidth(lower)+3,(linkWidth(lower)+3)*3.2);linksLayer.appendChild(sEl("path",{d:localLinkSegment(l,hit.t,fullLen),fill:"none",stroke:"#f7f4ed","stroke-width":linkWidth(l)+4,"stroke-linecap":"butt","stroke-linejoin":"round"}))}}for(const rp of linkRootPaths(l))linksLayer.appendChild(sEl("path",{d:rp.d,fill:"#f0c867"}));linksLayer.appendChild(sEl("path",{d:linkPath(l),class:"link-body","stroke-width":linkWidth(l)}))}for(const m of attachments){const e=mergeBridge(m,false);if(e)mergeLayer.appendChild(e)}}
function renderNodes(){nodesLayer.replaceChildren();const hidden=hiddenNodeMap();for(const n of sortedNodes()){const g=sEl("g",{"data-id":n.id}),blob=sEl("path",{d:circlePath(n.x,n.y,n.r),class:"node"});g.appendChild(blob);if(!hidden.has(n.id)){const text=sEl("text",{x:n.x,y:n.y,class:"label","font-size":Math.max(15,Math.min(22,n.r*.34))});text.textContent=n.label;g.appendChild(text)}nodesLayer.appendChild(g)}}
function linkNodeOverlapRanges(l,n){const runs=[];let start=null;for(let i=0;i<=90;i++){const t=i/90,p=quadPoint(l,t),inside=dist(p.x,p.y,n.x,n.y)<=n.r+4;if(inside&&start===null)start=t;if((!inside||i===90)&&start!==null){const end=inside?t:(i-1)/90;if(end-start>.008)runs.push([start,end]);start=null}}return runs}
function sampledLinkSegment(l,t0,t1,steps=14){let d="";for(let i=0;i<=steps;i++){const p=quadPoint(l,t0+(t1-t0)*i/steps);d+=(i?` L ${p.x} ${p.y}`:`M ${p.x} ${p.y}`)}return d}
function renderOverlapEdges(){overlapLayer.replaceChildren();for(const n of sortedNodes()){for(const l of links){if(l.a===n.id||l.b===n.id)continue;for(const [t0,t1] of linkNodeOverlapRanges(l,n)){overlapLayer.appendChild(sEl("path",{d:sampledLinkSegment(l,t0,t1),fill:"none",stroke:"#f7f4ed","stroke-width":linkWidth(l)+6,"stroke-linecap":"butt","stroke-linejoin":"round"}))}}}}
function circleCoveredArc(lower,upper){const dx=upper.x-lower.x,dy=upper.y-lower.y,d=Math.hypot(dx,dy);if(d>=lower.r+upper.r)return null;if(d+lower.r<=upper.r+.5)return{full:true};if(d+upper.r<=lower.r)return null;if(d<=1e-6)return upper.r>=lower.r?{full:true}:null;const theta=Math.atan2(dy,dx),c=clamp((d*d+lower.r*lower.r-upper.r*upper.r)/(2*d*lower.r),-1,1),alpha=Math.acos(c),a1=theta-alpha,a2=theta+alpha,p1={x:lower.x+Math.cos(a1)*(lower.r+2),y:lower.y+Math.sin(a1)*(lower.r+2)},p2={x:lower.x+Math.cos(a2)*(lower.r+2),y:lower.y+Math.sin(a2)*(lower.r+2)},large=alpha*2>Math.PI?1:0;return{full:false,d:`M ${p1.x} ${p1.y} A ${lower.r+2} ${lower.r+2} 0 ${large} 1 ${p2.x} ${p2.y}`}}
function hiddenCircleWithLinkGaps(n){const dirs=[];for(const l of links){if(l.a!==n.id&&l.b!==n.id)continue;const c=linkControl(l),d={x:c.x-n.x,y:c.y-n.y},a=Math.atan2(d.y,d.x),gap=Math.asin(clamp((linkWidth(l)*.62+5)/Math.max(n.r,1),0,.92))+.11;dirs.push({a,gap})}let d="",drawing=false;const steps=180,R=n.r+2;for(let i=0;i<=steps;i++){const a=-Math.PI+2*Math.PI*i/steps,inGap=dirs.some(g=>Math.abs(Math.atan2(Math.sin(a-g.a),Math.cos(a-g.a)))<g.gap),p={x:n.x+Math.cos(a)*R,y:n.y+Math.sin(a)*R};if(!inGap){d+=(drawing?` L ${p.x} ${p.y}`:`M ${p.x} ${p.y}`);drawing=true}else drawing=false}return d}
function hiddenLinkEdges(l,cover){const runs=linkNodeOverlapRanges(l,cover),out=[];for(const [t0,t1] of runs){for(const side of[-1,1]){let d="";const steps=18;for(let i=0;i<=steps;i++){const t=t0+(t1-t0)*i/steps,p=quadPoint(l,t),p0=quadPoint(l,clamp(t-.006,0,1)),p1=quadPoint(l,clamp(t+.006,0,1)),u=unit(p1.x-p0.x,p1.y-p0.y),v={x:-u.y,y:u.x},off=linkWidth(l)/2+2,q={x:p.x+v.x*off*side,y:p.y+v.y*off*side};d+=(i?` L ${q.x} ${q.y}`:`M ${q.x} ${q.y}`)}out.push(d)}}return out}
function renderHidden(){hiddenLayer.replaceChildren();const arr=sortedNodes();for(let i=0;i<arr.length;i++){const lower=arr[i];let fullCover=null;const arcs=[];for(let j=i+1;j<arr.length;j++){const upper=arr[j];if(sameComponent(lower.id,upper.id))continue;const arc=circleCoveredArc(lower,upper);if(!arc)continue;if(arc.full){fullCover=upper;break}arcs.push(arc.d)}if(fullCover){const d=hiddenCircleWithLinkGaps(lower);if(d)hiddenLayer.appendChild(sEl("path",{d,class:"hidden-outline"}));for(const l of links){if(l.a!==lower.id&&l.b!==lower.id)continue;for(const d2 of hiddenLinkEdges(l,fullCover))hiddenLayer.appendChild(sEl("path",{d:d2,class:"hidden-outline"}))}}else for(const d of arcs)hiddenLayer.appendChild(sEl("path",{d,class:"hidden-outline"}))}}
function hiddenNodeHit(x,y){const arr=sortedNodes();for(let i=arr.length-2;i>=0;i--){const lower=arr[i];if(dist(x,y,lower.x,lower.y)>lower.r+2/view.scale)continue;for(let j=i+1;j<arr.length;j++){const upper=arr[j];if(sameComponent(lower.id,upper.id))continue;if(dist(x,y,upper.x,upper.y)<=upper.r+2/view.scale)return lower}}return null}
function hiddenOutlineHit(x,y,maxD=10/view.scale){const hit=hiddenNodeHit(x,y);if(hit)return hit;const arr=sortedNodes();for(let i=arr.length-2;i>=0;i--){const lower=arr[i],radial=Math.abs(dist(x,y,lower.x,lower.y)-lower.r);if(radial>maxD)continue;for(let j=i+1;j<arr.length;j++){const upper=arr[j];if(sameComponent(lower.id,upper.id))continue;if(dist(x,y,upper.x,upper.y)<=upper.r+maxD*.3&&dist(lower.x,lower.y,upper.x,upper.y)<lower.r+upper.r)return lower}}return null}
function visibleWorldBounds(){return{left:-view.x/view.scale,right:(1000-view.x)/view.scale,top:-view.y/view.scale,bottom:(700-view.y)/view.scale}}
function mergeContactPoint(m){const a=nodeById(m.a),b=nodeById(m.b);if(!a||!b)return null;const u=unit(b.x-a.x,b.y-a.y),pa={x:a.x+u.x*a.r,y:a.y+u.y*a.r},pb={x:b.x-u.x*b.r,y:b.y-u.y*b.r};return{x:(pa.x+pb.x)/2,y:(pa.y+pb.y)/2,u}}
function renderUI(){uiLayer.replaceChildren();if(selected?.type==="node"){const n=nodeById(selected.id);if(n)uiLayer.appendChild(sEl("circle",{cx:n.x,cy:n.y,r:n.r+8/view.scale,class:"selection-ring"}))}else if(selected?.type==="link"){const l=linkById(selected.id);if(l)uiLayer.appendChild(sEl("path",{d:linkPath(l),class:"link-selection"}))}if(!gesture)return;if(gesture.mode==="resize"){const n=nodeById(gesture.nodeId);if(n)uiLayer.appendChild(sEl("circle",{cx:n.x,cy:n.y,r:n.r+16/view.scale,class:"resize-ring"}))}else if(gesture.mode==="linkEdit"){const l=linkById(gesture.linkId);if(l){const c=linkControl(l),a=nodeById(l.a),b=nodeById(l.b);uiLayer.appendChild(sEl("path",{d:`M ${a.x} ${a.y} L ${c.x} ${c.y} L ${b.x} ${b.y}`,class:"edit-guide"}));uiLayer.appendChild(sEl("circle",{cx:c.x,cy:c.y,r:10/view.scale,class:"edit-handle"}))}}else if(gesture.mode==="move"&&gesture.contactPair&&!gesture.crossMode){const a=nodeById(gesture.contactPair.movedId),b=nodeById(gesture.contactPair.otherId);if(a&&b){const u=unit(b.x-a.x,b.y-a.y),p={x:a.x+u.x*a.r,y:a.y+u.y*a.r},bounds=visibleWorldBounds(),w=224/view.scale,h=30/view.scale,x=clamp(p.x,bounds.left+w/2+8/view.scale,bounds.right-w/2-8/view.scale),y=clamp(p.y-44/view.scale,bounds.top+h/2+8/view.scale,bounds.bottom-h/2-8/view.scale),g=sEl("g");g.appendChild(sEl("rect",{x:x-w/2,y:y-h/2,width:w,height:h,rx:10/view.scale,class:"contact-hint-bg"}));const t=sEl("text",{x,y,class:"contact-hint","font-size":12/view.scale});t.textContent="離す＝くっつく　1.0秒＝交差";g.appendChild(t);uiLayer.appendChild(g)}}}
function renderNodesFast(){nodesLayer.replaceChildren();for(const n of sortedNodes()){const g=sEl("g",{"data-id":n.id}),blob=sEl("path",{d:circlePath(n.x,n.y,n.r),class:"node"}),text=sEl("text",{x:n.x,y:n.y,class:"label","font-size":Math.max(15,Math.min(22,n.r*.34))});text.textContent=n.label;g.append(blob,text);nodesLayer.appendChild(g)}}
function renderMotionNow(){shadowLayer.style.display="none";overlapLayer.style.display="none";hiddenLayer.style.display="none";renderLinks(true);renderNodesFast();renderUI()}
function scheduleMotionRender(){if(renderRAF)return;renderRAF=requestAnimationFrame(()=>{renderRAF=0;renderMotionNow()})}
function renderAll(){if(renderRAF){cancelAnimationFrame(renderRAF);renderRAF=0}shadowLayer.style.display="";overlapLayer.style.display="";hiddenLayer.style.display="";renderShadow();renderLinks(false);renderNodes();renderOverlapEdges();renderHidden();renderUI()}
function liveWidthFor(source,p){const pull=Math.max(0,dist(source.x,source.y,p.x,p.y)-source.r),t=clamp(pull/130,0,1);return LIVE_START_WIDTH+(LIVE_END_WIDTH-LIVE_START_WIDTH)*t}
function updateLiveSource(source,p){const width=liveWidthFor(source,p);if(!liveSourcePath){liveSourcePath=sEl("g",{id:"liveSourceGroup"});liveLayer.appendChild(liveSourcePath)}const pull=Math.max(0,dist(source.x,source.y,p.x,p.y)-source.r),rootProgress=clamp(pull/Math.max(width,1),0,1),rootD=rootPatchPath(source,{x:p.x-source.x,y:p.y-source.y},width,rootProgress),body=sEl("path",{d:`M ${source.x} ${source.y} L ${p.x} ${p.y}`,class:"link-body","stroke-width":width}),tip=sEl("circle",{cx:p.x,cy:p.y,r:width/2,class:"live-tip"}),els=[];if(rootD)els.push(sEl("path",{d:rootD,fill:"#f0c867"}));els.push(body,tip);liveSourcePath.replaceChildren(...els);return width}
function renderReceiver(){let g=liveLayer.querySelector("#receiverShape");if(!receiverState||receiverState.strength<=.01){g?.remove();return}const n=nodeById(receiverState.targetId),s=nodeById(receiverState.sourceId);if(!n||!s){g?.remove();return}if(!g){g=sEl("g",{id:"receiverShape"});liveLayer.appendChild(g)}const u=unit(s.x-n.x,s.y-n.y),ext=RECEIVER_MAX_EXTEND*clamp(receiverState.strength,0,1),width=receiverState.width||LINK_BASE_WIDTH,tip={x:n.x+u.x*(n.r+ext),y:n.y+u.y*(n.r+ext)},rootProgress=clamp(ext/Math.max(width,1),0,1),rootD=rootPatchPath(n,{x:u.x,y:u.y},width,rootProgress),body=sEl("path",{d:`M ${n.x} ${n.y} L ${tip.x} ${tip.y}`,class:"link-body","stroke-width":width}),cap=sEl("circle",{cx:tip.x,cy:tip.y,r:width/2,class:"live-tip"}),els=[];if(rootD)els.push(sEl("path",{d:rootD,fill:"#f0c867"}));els.push(body,cap);g.replaceChildren(...els)}
function setReceiver(sourceId,targetId,strength,width){cancelAnimationFrame(receiverRAF);receiverRAF=0;receiverState={sourceId,targetId,strength,width};renderReceiver()}
function retractReceiver(){if(!receiverState)return;cancelAnimationFrame(receiverRAF);const start=performance.now(),initial=receiverState.strength;function tick(now){const t=clamp((now-start)/130,0,1);receiverState.strength=initial*(1-t);renderReceiver();if(t<1)receiverRAF=requestAnimationFrame(tick);else{receiverState=null;renderReceiver();receiverRAF=0}}receiverRAF=requestAnimationFrame(tick)}
function clearLiveSource(){liveSourcePath?.remove();liveSourcePath=null}
function targetMetrics(source,target,p){const sp={x:p.x-source.x,y:p.y-source.y},st={x:target.x-source.x,y:target.y-source.y};return{angle:angleBetween(sp.x,sp.y,st.x,st.y),surfaceGap:dist(p.x,p.y,target.x,target.y)-target.r}}
function updateTargetLock(g,p){const source=nodeById(g.nodeId);if(!source)return null;if(g.lockId){const target=nodeById(g.lockId);if(target){const m=targetMetrics(source,target,p);if(m.angle<=RELEASE_ANGLE&&m.surfaceGap<=RELEASE_SURFACE)return{target,...m}}g.lockId=null;retractReceiver()}let best=null,bestScore=Infinity;for(const target of nodes){if(target.id===source.id)continue;const m=targetMetrics(source,target,p);if(m.angle<=ACQUIRE_ANGLE&&m.surfaceGap<=ACQUIRE_SURFACE){const score=m.angle*1200+Math.max(0,m.surfaceGap);if(score<bestScore){bestScore=score;best={target,...m}}}}if(best){g.lockId=best.target.id;return best}return null}
function quadPoint(l,t){const a=nodeById(l.a),b=nodeById(l.b),c=linkControl(l),u=1-t;return{x:u*u*a.x+2*u*t*c.x+t*t*b.x,y:u*u*a.y+2*u*t*c.y+t*t*b.y}}
function pointSegClosest(P,A,B){const dx=B.x-A.x,dy=B.y-A.y,den=dx*dx+dy*dy||1,t=clamp(((P.x-A.x)*dx+(P.y-A.y)*dy)/den,0,1),p={x:A.x+dx*t,y:A.y+dy*t};return{p,d:dist(P.x,P.y,p.x,p.y)}}
function nearestLink(x,y,maxD=24/view.scale){let best=null,bestD=Infinity;for(const l of links){let prev=quadPoint(l,0);for(let i=1;i<=30;i++){const cur=quadPoint(l,i/30),hit=pointSegClosest({x,y},prev,cur);if(hit.d<bestD&&hit.d<=maxD){best={link:l,d:hit.d,p:hit.p};bestD=hit.d}prev=cur}}return best}
function nearestMergeContact(x,y,maxD=34/view.scale){let best=null,bestD=Infinity;for(const m of attachments){const p=mergeContactPoint(m);if(!p)continue;const d=dist(x,y,p.x,p.y);if(d<bestD&&d<=maxD){best={merge:m,p,d};bestD=d}}return best}
function strokeLineSummary(points){if(points.length<2)return null;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity,len=0;for(let i=0;i<points.length;i++){const p=points[i];minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y);if(i)len+=dist(points[i-1].x,points[i-1].y,p.x,p.y)}const start=points[0],end=points.at(-1),direct=dist(start.x,start.y,end.x,end.y),size=Math.max(maxX-minX,maxY-minY);if(size<16/view.scale||size>260/view.scale||len<direct*.9)return null;return{start,end,mid:{x:(start.x+end.x)/2,y:(start.y+end.y)/2},angle:Math.atan2(end.y-start.y,end.x-start.x),size,direct}}
function segmentIntersection(A,B,C,D){const rx=B.x-A.x,ry=B.y-A.y,sx=D.x-C.x,sy=D.y-C.y,den=rx*sy-ry*sx;if(Math.abs(den)<1e-8)return null;const qx=C.x-A.x,qy=C.y-A.y,t=(qx*sy-qy*sx)/den,u=(qx*ry-qy*rx)/den;if(t>=0&&t<=1&&u>=0&&u<=1)return{x:A.x+t*rx,y:A.y+t*ry};return null}
function clearPendingX(){clearTimeout(firstXTimer);firstXTimer=0;firstXStroke=null;inkLayer.querySelector("#pendingX")?.remove()}
function acceptXStroke(points,inputType="pen"){const s=strokeLineSummary(points);if(!s){clearPendingX();return false}s.inputType=inputType;if(!firstXStroke){firstXStroke=s;const p=sEl("path",{id:"pendingX",d:`M ${s.start.x} ${s.start.y} L ${s.end.x} ${s.end.y}`,class:"pending-x"});inkLayer.appendChild(p);firstXTimer=setTimeout(clearPendingX,900);statusText("×の2画目を描く");return true}const angDiff=Math.abs(Math.atan2(Math.sin(s.angle-firstXStroke.angle),Math.cos(s.angle-firstXStroke.angle))),diff=Math.min(angDiff,Math.PI-angDiff),hit=segmentIntersection(firstXStroke.start,firstXStroke.end,s.start,s.end);if(diff>30*Math.PI/180&&hit&&dist(hit.x,hit.y,firstXStroke.mid.x,firstXStroke.mid.y)<130/view.scale){const type=inputType==="touch"||firstXStroke.inputType==="touch"?"touch":inputType;clearPendingX();deleteAt(hit,type);return true}clearPendingX();return false}
function deleteAt(p,inputType="pen"){const tol=(inputType==="touch"?54:inputType==="mouse"?28:58)/view.scale;let best=null,bestD=Infinity;for(const n of [...sortedNodes()].reverse()){const d=dist(p.x,p.y,n.x,n.y);if(d<=n.r+tol&&d<bestD){best=n;bestD=d}}if(best){requestDelete({type:"node",id:best.id});return}const l=nearestLink(p.x,p.y,(inputType==="mouse"?30:46)/view.scale);if(l){requestDelete({type:"link",id:l.link.id});return}statusText("×の近くに削除対象がありません")}
function requestDelete(c){deleteCandidate=c;if(c.type==="link"){performDelete();return}const d=degree(c.id);if(d>=3){deleteMsg.textContent=`この丸と接続 ${d} 本を削除しますか？`;confirmDelete.style.display="block"}else performDelete()}
function removeAttachmentsForNode(id){for(let i=attachments.length-1;i>=0;i--)if(attachments[i].a===id||attachments[i].b===id)attachments.splice(i,1)}
function performDelete(){if(!deleteCandidate)return;if(deleteCandidate.type==="link"){const i=links.findIndex(l=>l.id===deleteCandidate.id);if(i>=0)links.splice(i,1);statusText("紐を切断")}else{const id=deleteCandidate.id;removeAttachmentsForNode(id);for(let i=links.length-1;i>=0;i--)if(links[i].a===id||links[i].b===id)links.splice(i,1);for(const key of [...crossPairs])if(key.split('|').includes(id))crossPairs.delete(key);const i=nodes.findIndex(n=>n.id===id);if(i>=0)nodes.splice(i,1);statusText("丸を削除")}if(selected&&deleteCandidate&&selected.type===deleteCandidate.type&&selected.id===deleteCandidate.id)selected=null;deleteCandidate=null;confirmDelete.style.display="none";renderAll();commitHistory()}
