"use strict";
const F19_BUILD="0913-FIX19",F19_BOUNDARY="#c3922e",F19_BG="#f7f4ed";
function f19NormAngle(a){return Math.atan2(Math.sin(a),Math.cos(a))}
function f19Path(ps,close=false){if(!ps?.length)return"";let d=`M ${ps[0].x} ${ps[0].y}`;for(let i=1;i<ps.length;i++)d+=` L ${ps[i].x} ${ps[i].y}`;return d+(close?" Z":"")}
function f19Runs(test,pointAt,steps=360){const out=[];let cur=[];for(let i=0;i<=steps;i++){const p=pointAt(i/steps);if(test(p,i/steps))cur.push(p);else if(cur.length){if(cur.length>1)out.push(f19Path(cur));cur=[]}}if(cur.length>1)out.push(f19Path(cur));return out}

f18BulgedNodePath=function(n,toward,m){if(!n||!toward||!m?.visible)return circlePath(n.x,n.y,n.r);const base=Math.atan2(toward.y-n.y,toward.x-n.x),spread=1.03,pts=[];for(let i=0;i<120;i++){const a=-Math.PI+2*Math.PI*i/120,d=Math.abs(f19NormAngle(a-base));let bump=0;if(d<spread){const q=.5+.5*Math.cos(Math.PI*d/spread);bump=m.ext*q*q}const r=n.r+bump;pts.push({x:n.x+Math.cos(a)*r,y:n.y+Math.sin(a)*r})}return f19Path(pts,true)};

function f19NodeRimRuns(n){const nz=f14ObjectZ(n,"node"),R=n.r+1.6,lowerNodes=nodes.filter(o=>o.id!==n.id&&f14ObjectZ(o,"node")<nz&&!sameComponent(n.id,o.id)&&!linkExists(n.id,o.id)),lowerLinks=links.filter(l=>l.a!==n.id&&l.b!==n.id&&f14ObjectZ(l,"link")<nz);if(!lowerNodes.length&&!lowerLinks.length)return[];return f19Runs(p=>lowerNodes.some(o=>dist(p.x,p.y,o.x,o.y)<o.r-.15)||lowerLinks.some(l=>f15PointLinkDistance(l,p,110)<=linkWidth(l)/2+1.6),t=>{const a=-Math.PI+2*Math.PI*t;return{x:n.x+Math.cos(a)*R,y:n.y+Math.sin(a)*R}},360)}
f18DecorateNodeOverlap=function(n,g){if(!n||!g)return;g.querySelectorAll('[data-upper-rim="1"],[data-overlap-rim]').forEach(e=>e.remove());for(const d of f19NodeRimRuns(n))g.appendChild(sEl("path",{d,fill:"none",stroke:F19_BOUNDARY,"stroke-width":3,"stroke-linecap":"round","stroke-linejoin":"round","data-overlap-rim":"f19-unified"}))};

function f19FullyCovered(n,c){return dist(n.x,n.y,c.x,c.y)+n.r<=c.r+.75}
function f19PartiallyCovered(n,c){const d=dist(n.x,n.y,c.x,c.y);return d<n.r+c.r&&!f19FullyCovered(n,c)&&!(d+c.r<=n.r)}
f18RenderHidden=function(){hiddenLayer.replaceChildren();const ordered=[...nodes].sort((a,b)=>f14ObjectZ(a,"node")-f14ObjectZ(b,"node")||((a.created??0)-(b.created??0)));for(let i=0;i<ordered.length;i++){const lower=ordered[i];for(let j=i+1;j<ordered.length;j++){const upper=ordered[j];if(sameComponent(lower.id,upper.id))continue;const arc=circleCoveredArc(lower,upper);if(!arc)continue;if(arc.full){const d=hiddenCircleWithLinkGaps(lower);if(d)hiddenLayer.appendChild(sEl("path",{d,class:"hidden-outline","data-hidden-node":lower.id,"data-full-cover":"1","data-cover":upper.id,"data-f19":"1"}));break}hiddenLayer.appendChild(sEl("path",{d:arc.d,class:"hidden-outline","data-hidden-node":lower.id,"data-cover":upper.id,"data-partial":"1","data-f19":"1"}))}}for(const cover of ordered)for(const l of links){if(l.a===cover.id||l.b===cover.id)continue;for(const d of hiddenLinkEdges(l,cover))hiddenLayer.appendChild(sEl("path",{d,class:"hidden-outline","data-hidden-link":l.id,"data-cover":cover.id,"data-f19":"1"}));if(typeof f12HiddenRootEdges!=="function")continue;const ends=[nodeById(l.a),nodeById(l.b)].filter(Boolean).filter(ep=>f14ObjectZ(ep,"node")<f14ObjectZ(cover,"node")&&!sameComponent(ep.id,cover.id));if(!ends.some(ep=>f19PartiallyCovered(ep,cover))||ends.some(ep=>f19FullyCovered(ep,cover)))continue;for(const d of f12HiddenRootEdges(l,cover))hiddenLayer.appendChild(sEl("path",{d,class:"hidden-outline","data-hidden-root":l.id,"data-cover":cover.id,"data-partial-root":"1","data-f19":"1"}))}};
renderHidden=f18RenderHidden;

function f19ExpandRange(l,t0,t1,pixels=5){let a=t0,b=t1;if(typeof f17ArcLenToT==="function"){a=f17ArcLenToT(l,t0,-1,pixels,0);b=f17ArcLenToT(l,t1,1,pixels,1)}return[Math.max(.015,a),Math.min(.985,b)]}
f18RenderZBoundaries=function(){f14NormalizeLinkZ();overlapLayer.replaceChildren();f15ZTopLayer.replaceChildren();const ordered=[...links].sort((a,b)=>f14ObjectZ(a,"link")-f14ObjectZ(b,"link")||((a.seq??0)-(b.seq??0)));for(let i=1;i<ordered.length;i++){const upper=ordered[i];for(let j=0;j<i;j++){const lower=ordered[j];for(const raw of f15LinkLinkRanges(upper,lower)){const range=typeof f17CompactRange==="function"?f17CompactRange(upper,lower,raw[0],raw[1]):raw,t0=range[0],t1=range[1];if(t1<=t0)continue;overlapLayer.appendChild(sEl("path",{d:f15RangePath(upper,t0,t1),fill:"none",stroke:F19_BG,"stroke-width":linkWidth(upper)+5,"stroke-linecap":"butt","data-z-boundary":"link-link-gap","data-f19":"1"}));const ex=f19ExpandRange(upper,t0,t1);overlapLayer.appendChild(sEl("path",{d:f15RangePath(upper,ex[0],ex[1]),fill:"none",stroke:"#f0c867","stroke-width":linkWidth(upper),"stroke-linecap":"round","data-z-boundary":"link-link-top","data-f19":"1"}))}}}for(const l of links){const lz=f14ObjectZ(l,"link");for(const n of nodes){if(l.a===n.id||l.b===n.id||f14ObjectZ(n,"node")>=lz)continue;for(const[t0,t1]of linkNodeOverlapRanges(l,n)){const d=f15RangePath(l,t0,t1);f15ZTopLayer.appendChild(sEl("path",{d,fill:"none",stroke:F19_BG,"stroke-width":linkWidth(l)+4,"stroke-linecap":"butt","data-z-boundary":"link-node-gap"}));f15ZTopLayer.appendChild(sEl("path",{d,fill:"none",stroke:"#f0c867","stroke-width":linkWidth(l),"stroke-linecap":"round","data-z-boundary":"link-node-top"}))}}}};
f15RenderZBoundaries=f18RenderZBoundaries;renderOverlapEdges=f18RenderZBoundaries;
renderAll=function(){if(renderRAF){cancelAnimationFrame(renderRAF);renderRAF=0}shadowLayer.style.display="";overlapLayer.style.display="";hiddenLayer.style.display="";renderShadow();renderLinks(false);renderNodes();f18RenderZBoundaries();f18RenderHidden();renderUI()};
renderMotionNow=function(){shadowLayer.style.display="none";hiddenLayer.style.display="";renderLinks(true);renderNodes();f18RenderZBoundaries();f18RenderHidden();renderUI()};
window.__mochiFix19Test={bulgedNodePath:f18BulgedNodePath,nodeRimRuns:f19NodeRimRuns,renderHidden:f18RenderHidden,renderBoundaries:f18RenderZBoundaries,stretchStartFrac:typeof F18_STRETCH_START_FRAC!=="undefined"?F18_STRETCH_START_FRAC:null};statusText=function(t){status.innerHTML=`餅マップ v0.9.4<br>BUILD ${F19_BUILD}<br>${t}`};statusText("待機中");
