"use strict";
const svg=document.getElementById("stage"),world=document.getElementById("world"),shadowLayer=document.getElementById("shadowLayer"),linksLayer=document.getElementById("linksLayer"),mergeLayer=document.getElementById("mergeLayer"),liveLayer=document.getElementById("liveLayer"),nodesLayer=document.getElementById("nodesLayer"),overlapLayer=document.getElementById("overlapLayer"),hiddenLayer=document.getElementById("hiddenLayer"),inkLayer=document.getElementById("inkLayer"),uiLayer=document.getElementById("uiLayer"),status=document.getElementById("status"),fitBtn=document.getElementById("fitBtn"),selectBtn=document.getElementById("selectBtn"),eraseBtn=document.getElementById("eraseBtn"),newBtn=document.getElementById("newBtn"),undoBtn=document.getElementById("undoBtn"),redoBtn=document.getElementById("redoBtn"),contextMenu=document.getElementById("contextMenu"),ctxSelect=document.getElementById("ctxSelect"),ctxNew=document.getElementById("ctxNew"),ctxDelete=document.getElementById("ctxDelete"),confirmDelete=document.getElementById("confirmDelete"),deleteMsg=document.getElementById("deleteMsg"),cancelDelete=document.getElementById("cancelDelete"),doDelete=document.getElementById("doDelete");
const DEFAULT_R=82,MIN_R=34,MAX_R=1000000,LINK_BASE_WIDTH=30,MIN_NEW_R=34,MAX_NEW_R=1000000,EDIT_HOLD_MS=400,CONTACT_HOLD_MS=1000,MOVE_THRESHOLD=9,PEN_MOVE_THRESHOLD=7;
const LIVE_START_WIDTH=46,LIVE_END_WIDTH=28,ATTACH_OVERLAP=8,DETACH_SHIFT=28,CONTACT_EPS=1.5,PIVOT_SNAP=5;
const ACQUIRE_ANGLE=3*Math.PI/180,RELEASE_ANGLE=5*Math.PI/180,ACQUIRE_SURFACE=120,RELEASE_SURFACE=145,RECEIVER_MAX_EXTEND=34,VIEW_MIN=.22,VIEW_MAX=3.5;
let zSeq=2,createSeq=2,attachSeq=0;
const nodes=[{id:"a",x:315,y:350,r:DEFAULT_R,label:"アイデアA",z:1,created:1},{id:"b",x:685,y:350,r:DEFAULT_R,label:"アイデアB",z:2,created:2}],links=[],attachments=[],crossPairs=new Set();
let linkSeq=1,newNodeNo=1,gesture=null,liveSourcePath=null,receiverState=null,receiverRAF=0,view={x:0,y:0,scale:1};
const touches=new Map();let touchViewGesture=null,firstXStroke=null,firstXTimer=0,deleteCandidate=null,pcTool=null,selected=null,contextTarget=null,contextPoint=null;
const historyPast=[],historyFuture=[];let renderRAF=0;
function sEl(tag,attrs={}){const e=document.createElementNS("http://www.w3.org/2000/svg",tag);for(const[k,v]of Object.entries(attrs))if(v!==undefined&&v!==null)e.setAttribute(k,v);return e}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function dist(x1,y1,x2,y2){return Math.hypot(x2-x1,y2-y1)}
function unit(dx,dy){const d=Math.hypot(dx,dy)||1;return{x:dx/d,y:dy/d}}
function nodeById(id){return nodes.find(n=>n.id===id)}
function linkById(id){return links.find(l=>l.id===id)}
function pairKey(a,b){return a<b?`${a}|${b}`:`${b}|${a}`}
function snapshotState(){return{nodes:structuredClone(nodes),links:structuredClone(links),attachments:structuredClone(attachments),crossPairs:[...crossPairs],zSeq,createSeq,attachSeq,linkSeq,newNodeNo}}
function snapshotKey(s){return JSON.stringify(s)}
function restoreState(s){nodes.splice(0,nodes.length,...structuredClone(s.nodes));links.splice(0,links.length,...structuredClone(s.links));attachments.splice(0,attachments.length,...structuredClone(s.attachments));crossPairs.clear();for(const k of s.crossPairs)crossPairs.add(k);zSeq=s.zSeq;createSeq=s.createSeq;attachSeq=s.attachSeq;linkSeq=s.linkSeq;newNodeNo=s.newNodeNo;selected=null;gesture=null;clearLiveSource();receiverState=null;renderAll()}
function updateHistoryButtons(){undoBtn.disabled=historyPast.length<=1;redoBtn.disabled=historyFuture.length===0}
function commitHistory(){const s=snapshotState(),k=snapshotKey(s);if(!historyPast.length||snapshotKey(historyPast.at(-1))!==k){historyPast.push(s);if(historyPast.length>80)historyPast.shift();historyFuture.length=0}updateHistoryButtons()}
function undo(){if(historyPast.length<=1)return;historyFuture.push(historyPast.pop());restoreState(historyPast.at(-1));updateHistoryButtons();statusText("戻しました")}
function redo(){if(!historyFuture.length)return;const s=historyFuture.pop();historyPast.push(s);restoreState(s);updateHistoryButtons();statusText("進めました")}
function statusText(t){status.innerHTML=`餅マップ v0.9.4<br>BUILD 0909-FIX5<br>${t}`}
function clientToSvg(evt){const p=svg.createSVGPoint();p.x=evt.clientX;p.y=evt.clientY;return p.matrixTransform(svg.getScreenCTM().inverse())}
function svgToWorldPoint(p){return{x:(p.x-view.x)/view.scale,y:(p.y-view.y)/view.scale}}
function eventToWorld(evt){return svgToWorldPoint(clientToSvg(evt))}
function applyView(){world.setAttribute("transform",`translate(${view.x} ${view.y}) scale(${view.scale})`)}
function circlePath(cx,cy,r){return`M ${cx-r} ${cy} a ${r} ${r} 0 1 0 ${r*2} 0 a ${r} ${r} 0 1 0 ${-r*2} 0`}
function angleBetween(ax,ay,bx,by){const ad=Math.hypot(ax,ay),bd=Math.hypot(bx,by);if(ad<1e-6||bd<1e-6)return Math.PI;return Math.acos(clamp((ax*bx+ay*by)/(ad*bd),-1,1))}
function sortedNodes(){return [...nodes].sort((a,b)=>(a.z??0)-(b.z??0)||((a.created??0)-(b.created??0)))}
function nearestNode(x,y){let best=null,bestD=Infinity;for(const n of [...sortedNodes()].reverse()){const d=dist(x,y,n.x,n.y);if(d<=n.r+24/view.scale&&d<bestD){best={node:n,d};bestD=d}}return best}
function linkExists(a,b){return links.some(l=>(l.a===a&&l.b===b)||(l.a===b&&l.b===a))}
function directAttached(a,b){return attachments.some(m=>(m.a===a&&m.b===b)||(m.a===b&&m.b===a))}
function degree(id){return links.filter(l=>l.a===id||l.b===id).length}
function linkWidth(){return LINK_BASE_WIDTH}
function componentIds(startId){const seen=new Set([startId]),q=[startId];while(q.length){const id=q.shift();for(const m of attachments){let other=null;if(m.a===id)other=m.b;else if(m.b===id)other=m.a;if(other&&!seen.has(other)){seen.add(other);q.push(other)}}}return [...seen]}
function sameComponent(a,b){return componentIds(a).includes(b)}
function bringComponentFront(ids){const arr=ids.map(nodeById).filter(Boolean).sort((a,b)=>(a.z??0)-(b.z??0));for(const n of arr)n.z=++zSeq}
function fitAll(){if(!nodes.length)return;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const n of nodes){minX=Math.min(minX,n.x-n.r);maxX=Math.max(maxX,n.x+n.r);minY=Math.min(minY,n.y-n.r);maxY=Math.max(maxY,n.y+n.r)}for(const l of links){if(l.control){minX=Math.min(minX,l.control.x);maxX=Math.max(maxX,l.control.x);minY=Math.min(minY,l.control.y);maxY=Math.max(maxY,l.control.y)}}const margin=95,w=Math.max(80,maxX-minX),h=Math.max(80,maxY-minY),s=clamp(Math.min((1000-margin*2)/w,(700-margin*2)/h),VIEW_MIN,2.2),cx=(minX+maxX)/2,cy=(minY+maxY)/2;view.scale=s;view.x=500-cx*s;view.y=350-cy*s;applyView();renderAll();statusText("全体表示")}

function startSinglePan(){if(touches.size!==1)return;const[id,p]=[...touches.entries()][0];if(p.role!=="pan")return;touchViewGesture={mode:"pan",id,start:{x:p.x,y:p.y},startView:{x:view.x,y:view.y}}}
function startPinch(){if(touches.size<2)return;const vals=[...touches.values()].slice(0,2),a=vals[0],b=vals[1],c={x:(a.x+b.x)/2,y:(a.y+b.y)/2},d=dist(a.x,a.y,b.x,b.y)||1,anchor={x:(c.x-view.x)/view.scale,y:(c.y-view.y)/view.scale};touchViewGesture={mode:"pinch",startDist:d,startScale:view.scale,anchor}}
function restoreGestureForPinch(){if(!gesture)return;cancelHold();clearContactTimer(gesture);if(gesture.mode==="move"||gesture.mode==="pivot")restoreMoveStart(gesture);else if(gesture.mode==="resize"){const n=nodeById(gesture.nodeId);if(n&&gesture.startR!=null)n.r=gesture.startR}else if(gesture.mode==="linkEdit"){const l=linkById(gesture.linkId);if(l)l.control=gesture.originalControl?{...gesture.originalControl}:null}else if(gesture.mode==="stretch"){clearLiveSource();retractReceiver()}inkLayer.querySelector("#activeInk")?.remove();gesture=null;renderAll()}
function touchObjectHit(p){if(hiddenOutlineHit(p.x,p.y))return true;if(nearestMergeContact(p.x,p.y,22/view.scale))return true;const n=nearestNode(p.x,p.y);if(n&&n.d<=n.node.r+38/view.scale)return true;if(nearestLink(p.x,p.y,34/view.scale))return true;return false}
function touchDown(evt){evt.preventDefault();const p=clientToSvg(evt),w=eventToWorld(evt);touches.set(evt.pointerId,{x:p.x,y:p.y,role:null});svg.setPointerCapture?.(evt.pointerId);if(touches.size>=2){restoreGestureForPinch();for(const t of touches.values())t.role="pinch";startPinch();return}const rec=touches.get(evt.pointerId);if(firstXStroke){rec.role="object";penDown(evt,true);return}if(touchObjectHit(w)){rec.role="object";penDown(evt,true)}else{selected=null;rec.role="pan";startSinglePan();renderUI()}}
function touchMove(evt){const rec=touches.get(evt.pointerId);if(!rec)return;evt.preventDefault();const p=clientToSvg(evt);rec.x=p.x;rec.y=p.y;if(touches.size>=2){if(!touchViewGesture||touchViewGesture.mode!=="pinch")startPinch();const vals=[...touches.values()].slice(0,2),a=vals[0],b=vals[1],c={x:(a.x+b.x)/2,y:(a.y+b.y)/2},d=dist(a.x,a.y,b.x,b.y)||1,s=clamp(touchViewGesture.startScale*(d/touchViewGesture.startDist),VIEW_MIN,VIEW_MAX);view.scale=s;view.x=c.x-touchViewGesture.anchor.x*s;view.y=c.y-touchViewGesture.anchor.y*s;applyView();renderUI();return}if(rec.role==="object"){penMove(evt);return}if(rec.role==="pan"){if(!touchViewGesture||touchViewGesture.mode!=="pan")startSinglePan();if(!touchViewGesture||touchViewGesture.id!==evt.pointerId)return;view.x=touchViewGesture.startView.x+(rec.x-touchViewGesture.start.x);view.y=touchViewGesture.startView.y+(rec.y-touchViewGesture.start.y);applyView();renderUI()}}
function touchEnd(evt){const rec=touches.get(evt.pointerId);if(!rec)return;evt.preventDefault();if(rec.role==="object"&&gesture?.pointerId===evt.pointerId)penEnd(evt);touches.delete(evt.pointerId);if(touches.size>=2)startPinch();else if(touches.size===1){const only=[...touches.values()][0];only.role="pan";startSinglePan()}else touchViewGesture=null}
svg.addEventListener("wheel",evt=>{evt.preventDefault();if(evt.ctrlKey){const p=clientToSvg(evt),anchor=svgToWorldPoint(p),factor=Math.exp(-evt.deltaY*.006),s=clamp(view.scale*factor,VIEW_MIN,VIEW_MAX);view.scale=s;view.x=p.x-anchor.x*s;view.y=p.y-anchor.y*s;applyView();renderUI();statusText(`ズーム ${Math.round(s*100)}%`);return}const m=svg.getScreenCTM(),sx=Math.abs(m?.a)||1,sy=Math.abs(m?.d)||1;view.x-=evt.deltaX/sx;view.y-=evt.deltaY/sy;applyView();renderUI();statusText("パン")},{passive:false});
